
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(randomForest)
library(tidyverse)
library(ipred)
library(caTools)
```

```{r}
#read in csv file
churn_df <- read.csv("/Users/wyattromero/Downloads/RandomForest/churn_clean.csv")
head(churn_df)
```

```{r}
summary(churn_df)
```

```{r}
str(churn_df)
```

```{r}
#Rename survey variables for clarity
churn_df <- rename(churn_df, 'TimelyResponse' = 'Item1',
       'Fixes' = 'Item2',
       'Replacements' = 'Item3',
       'Reliability' = 'Item4',
       'Options' = 'Item5',
       'Respectfulness' = 'Item6',
       'Courteous' = 'Item7',
       'Listening' = 'Item8')
```

```{r}
churn_df$Gender <- ifelse(churn_df$Gender == "Female", 1, 0)
churn_df$Churn <- ifelse(churn_df$Churn == "Yes", 1, 0)
churn_df$Techie <- ifelse(churn_df$Techie == "Yes", 1, 0)
churn_df$Contract <- ifelse(churn_df$Contract == "Two Year", 1, 0)
churn_df$Port_modem <- ifelse(churn_df$Port_modem == "Yes", 1, 0)
churn_df$Tablet <- ifelse(churn_df$Tablet == "Yes", 1, 0)
churn_df$InternetService <- ifelse(churn_df$InternetService == "Fiber Optic", 1, 0)
churn_df$Phone <- ifelse(churn_df$Phone == "Yes", 1, 0)
churn_df$Multiple <- ifelse(churn_df$Multiple == "Yes", 1, 0)
churn_df$OnlineSecurity <- ifelse(churn_df$OnlineSecurity == "Yes", 1, 0)
churn_df$OnlineBackup <- ifelse(churn_df$OnlineBackup == "Yes", 1, 0)
churn_df$DeviceProtection <- ifelse(churn_df$DeviceProtection == "Yes", 1, 0)
churn_df$TechSupport <- ifelse(churn_df$TechSupport == "Yes", 1, 0)
churn_df$StreamingTV <- ifelse(churn_df$StreamingTV == "Yes", 1, 0)
churn_df$StreamingMovies <- ifelse(churn_df$StreamingMovies == "Yes", 1, 0)
churn_df$PaperlessBilling <- ifelse(churn_df$PaperlessBilling == "Yes", 1, 0)
head(churn_df)
```

```{r}
churn_df <- select(churn_df, -c('Population', 'CaseOrder', 'Customer_id', 'Interaction', 'UID', 'City', 'State', 'County', 'Zip', 'Lat', 'Lng', 'Area', 'TimeZone', 'Job', 'Marital', 'PaymentMethod', 'TimelyResponse', 'Fixes', 'Replacements', 'Reliability', 'Options', 'Respectfulness', 'Courteous', 'Listening'))
head(churn_df)
```

```{r}
churn_df <- select(churn_df, c('Children', 'Age', 'Income', 'MonthlyCharge', 'Outage_sec_perweek', 'Yearly_equip_failure', 'Tenure','Bandwidth_GB_Year'))
head(churn_df)
```

```{r}
dim(churn_df)
```

```{r}
churn_df[ churn_df == "?"] <- NA
colSums(is.na(churn_df))
```

```{r}
write.csv(churn_df, "churn_prepared_D209_2.csv", row.names = TRUE)
```

```{r}
#Data splitting
set.seed(1)
split <- sample.split(churn_df, SplitRatio = 0.7)
train <- subset(churn_df, split == "TRUE")
test <- subset(churn_df, split == "FALSE")

dim(train)
dim(test)
```

```{r}
write.csv(train, "train_dataset_D209_2", row.names = TRUE)
write.csv(test, "test_dataset_D209_2", row.names = TRUE)
```

```{r}
set.seed(2)
rf <- randomForest(
  formula = Bandwidth_GB_Year ~ .,
  data = train,
  mtry = 3,
  ntree = 500,
  importance = TRUE,
  type = "regression", 
  na.action = na.omit
)
rf
```

```{r}
mse <- which.min(rf$mse)
mse
accuracy <- 1 - (mse / 500)
accuracy
```

```{r}
plot(rf)
```

```{r}
varImpPlot(rf)
```

```{r}
new <- data.frame(MonthlyCharge=242.6326, Tenure=1.156681, Children=1, Income=21704.77, Outage_sec_perweek=11.699, Yearly_equip_failure=1, Age=27)
bandwidth_gb_year_pred <- predict(rf, newdata=new)
bandwidth_gb_year_pred
```